import Header from '@/components/Header/Header';
import './globals.css'
import Navbar from '@/components/Navbar/Navbar';
import SearchBox from '@/components/SearchBox/SearchBox';

export const metadata = {
  title: 'IMDb Clone',
  description: 'Generated by create next app',
  viewport: {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1,
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* Header */}
        <Header />
        
        {/* Navbar */}
        <Navbar />
        
        {/* Search Box */}
        <SearchBox />

        {children}
      </body>
    </html>
  )
}
